version: '3.8'

services:
  # ClickHouse - Columnar analytical database (isolated)
  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    container_name: benchmark_clickhouse_isolated
    ports:
      - "8123:8123"  # HTTP port
      - "9000:9000"  # Native port
    volumes:
      - clickhouse_data_isolated:/var/lib/clickhouse
      - ./init-scripts/clickhouse:/docker-entrypoint-initdb.d
      - ./config/clickhouse/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./config/clickhouse/users.xml:/etc/clickhouse-server/users.d/users.xml
    networks:
      - benchmark_network
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Redis for caching (lightweight support)
  redis:
    image: redis:7-alpine
    container_name: benchmark_redis_isolated
    ports:
      - "6379:6379"
    networks:
      - benchmark_network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  clickhouse_data_isolated:

networks:
  benchmark_network:
    driver: bridge
