version: '3.8'

services:
  # TimescaleDB - Time-series PostgreSQL extension (isolated)
  timescaledb:
    image: timescale/timescaledb:2.11.2-pg15
    container_name: benchmark_timescaledb_isolated
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: benchmark
      POSTGRES_USER: benchmark_user
      POSTGRES_PASSWORD: benchmark_pass
      TIMESCALEDB_TELEMETRY: off
    volumes:
      - timescale_data_isolated:/var/lib/postgresql/data
      - ./init-scripts/timescale:/docker-entrypoint-initdb.d
    networks:
      - benchmark_network
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U benchmark_user -d benchmark"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Redis for caching (lightweight support)
  redis:
    image: redis:7-alpine
    container_name: benchmark_redis_isolated
    ports:
      - "6379:6379"
    networks:
      - benchmark_network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  timescale_data_isolated:

networks:
  benchmark_network:
    driver: bridge
