global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'scylladb'
    static_configs:
      - targets: ['scylladb:9180']
    scrape_interval: 30s
    metrics_path: /metrics

  - job_name: 'clickhouse'
    static_configs:
      - targets: ['clickhouse:9363']
    scrape_interval: 30s
    metrics_path: /metrics

  - job_name: 'timescaledb'
    static_configs:
      - targets: ['timescaledb:5432']
    scrape_interval: 30s
    metrics_path: /metrics

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
